"""
Django settings for task_api project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
import dj_database_url  # Thư viện hỗ trợ database cho Render

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xd(lsvr(l!u(5l2x3kk$x^qesu6w@3#5zt-wv01^&uk!(uxz3_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Cho phép chạy trên mọi host (Cần thiết cho Render)
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Bên thứ 3
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders', # CORS

    # App của bạn
    'tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'task_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'task_api.wsgi.application'


# ================= DATABASE CONFIGURATION (Thông minh) =================
# Logic: Nếu có biến môi trường RENDER (trên server) -> Dùng PostgreSQL
#        Nếu không (trên máy bạn) -> Dùng SQL Server (SSMS)

if 'RENDER' in os.environ:
    # === CẤU HÌNH CHO SERVER (PostgreSQL) ===
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # === CẤU HÌNH CHO MÁY BẠN (SQL Server - SSMS) ===
    DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'TaskManagerDB',
        'HOST': '127.0.0.1',
        'PORT': '50034',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # 🔹 dùng đúng driver bạn chọn
            'Trusted_Connection': 'yes',
        },
    }
}
# =======================================================================


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ================= STATIC FILES (CSS, JS, Images) =================
# Cấu hình này giúp Render nhận diện và phục vụ file tĩnh

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ================= REST FRAMEWORK & CORS =================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

ALLOWED_HOSTS = ['*']

# Cho phép mọi nguồn truy cập (Tạm thời để True cho dễ chạy)
CORS_ALLOW_ALL_ORIGINS = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'