# Generated by Django 5.2.7 on 2025-11-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_workspacemember'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together=set(),
        ),
    ]
