# Generated by Django 5.2.7 on 2025-11-12 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_workspacemember_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('TODO', 'Đang làm'), ('DONE', 'Đã xong'), ('CANCELLED', 'Đã hủy')], default='TODO', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='workspaces', through='tasks.WorkspaceMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
