# Generated by Django 5.2.7 on 2025-11-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_workspace_deleted_at_workspace_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
